// scripts/gen-api-client.ts
// Generates the typed API client for BOTH apps from server/contract.
//   npm run gen:api            write everything
//   npm run gen:api -- --check fail (exit 1) if any generated file is stale
//
// Same idea as scripts/gen-role-capabilities.mjs and regen-types.sh: shared
// logic is generated from one source, never copy-edited per app.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import { buildOpenApi } from '../server/contract/openapi'

const WEB = path.resolve(__dirname, '..')
const MOBILE = path.resolve(WEB, '../carrieros-mobile')
const CHECK = process.argv.includes('--check')

const HEADER = (what: string) =>
  `// GENERATED by carrieros-web/scripts/gen-api-client.ts -- do not edit.\n// ${what}\n// Change server/contract/*, then run \`npm run gen:api\` in carrieros-web.\n\n`

async function main() {
  const doc = buildOpenApi()
  const openapiJson = JSON.stringify(doc, null, 2) + '\n'
  const types = HEADER('Types derived from the OpenAPI document built from server/contract.') +
    astToString(await openapiTS(doc as never))
  const template = (name: string) =>
    HEADER('Shared client runtime (source: carrieros-web/scripts/api-client-template).') +
    readFileSync(path.join(WEB, 'scripts/api-client-template', name), 'utf8')

  const outputs: Record<string, string> = {
    [path.join(WEB, 'server/contract/openapi.json')]: openapiJson,
  }
  for (const dir of [path.join(WEB, 'lib/generated'), path.join(MOBILE, 'src/lib/generated')]) {
    outputs[path.join(dir, 'api-types.ts')] = types
    outputs[path.join(dir, 'api-client.ts')] = template('api-client.ts')
    outputs[path.join(dir, 'live-refresh.ts')] = template('live-refresh.ts')
  }

  const stale: string[] = []
  for (const [file, content] of Object.entries(outputs)) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null
    if (current === content) continue
    if (CHECK) stale.push(path.relative(path.resolve(WEB, '..'), file))
    else {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, content)
      console.log('wrote', path.relative(path.resolve(WEB, '..'), file))
    }
  }
  if (CHECK) {
    if (stale.length) {
      console.error('Generated API client is out of date:\n  ' + stale.join('\n  ') + '\nRun `npm run gen:api` in carrieros-web and commit the result.')
      process.exit(1)
    }
    console.log('API client is up to date.')
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
