// Committed on purpose: expo-env.d.ts (which normally provides these) is
// generated by `expo start` and gitignored, so a fresh checkout -- CI -- would
// fail to typecheck imports of stylesheets.
/// <reference types="expo/types" />
declare module '*.css';
