-- Append-only, low-sensitivity write activity for support/security investigation.
-- Store action + record identity only (never row payloads, message bodies, or secrets).
CREATE TABLE tenant_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  actor_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT,
  operation TEXT NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tenant_activity_actor_time ON tenant_activity_events(org_id, actor_user_id, occurred_at DESC);
CREATE INDEX idx_tenant_activity_record_time ON tenant_activity_events(org_id, aggregate_type, aggregate_id, occurred_at DESC);
ALTER TABLE tenant_activity_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON tenant_activity_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON tenant_activity_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE tenant_activity_events_id_seq TO service_role;
COMMENT ON TABLE tenant_activity_events IS
  'Append-only, payload-free audit of writes to selected tenant records. Does not record reads, failed requests, or auth session/IP/device history.';

CREATE OR REPLACE FUNCTION capture_tenant_activity() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_row JSONB := to_jsonb(CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END);
  v_org BIGINT := NULLIF(v_row ->> TG_ARGV[1], '')::BIGINT;
  v_id TEXT := NULLIF(v_row ->> 'id', '');
BEGIN
  IF v_org IS NOT NULL THEN
    INSERT INTO tenant_activity_events(org_id, actor_user_id, action, aggregate_type, aggregate_id, operation)
    VALUES (v_org, auth.uid(), lower(TG_ARGV[0]) || '.' || lower(TG_OP), TG_ARGV[0], v_id, TG_OP);
  END IF;
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION capture_load_event_activity() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_load_id BIGINT := CASE WHEN TG_OP = 'DELETE' THEN OLD.load_id ELSE NEW.load_id END;
  v_event_id BIGINT := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  v_org BIGINT;
BEGIN
  SELECT carrier_org_id INTO v_org FROM loads WHERE id = v_load_id;
  IF v_org IS NOT NULL THEN
    INSERT INTO tenant_activity_events(org_id, actor_user_id, action, aggregate_type, aggregate_id, operation)
    VALUES (v_org, auth.uid(), 'load_event.' || lower(TG_OP), 'load_event', v_event_id::TEXT, TG_OP);
  END IF;
  RETURN NULL;
END $$;

REVOKE EXECUTE ON FUNCTION capture_tenant_activity() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION capture_load_event_activity() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER tenant_activity_loads AFTER INSERT OR UPDATE OR DELETE ON loads
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('load', 'carrier_org_id');
CREATE TRIGGER tenant_activity_invoices AFTER INSERT OR UPDATE OR DELETE ON invoices
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('invoice', 'carrier_org_id');
CREATE TRIGGER tenant_activity_vehicles AFTER INSERT OR UPDATE OR DELETE ON vehicles
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('vehicle', 'carrier_org_id');
CREATE TRIGGER tenant_activity_drivers AFTER INSERT OR UPDATE OR DELETE ON drivers
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('driver', 'carrier_org_id');
CREATE TRIGGER tenant_activity_profiles AFTER INSERT OR UPDATE OR DELETE ON profiles
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('profile', 'org_id');
CREATE TRIGGER tenant_activity_customers AFTER INSERT OR UPDATE OR DELETE ON customer_details
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('customer_account', 'carrier_org_id');
CREATE TRIGGER tenant_activity_documents AFTER INSERT OR UPDATE OR DELETE ON documents
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('document', 'carrier_org_id');
CREATE TRIGGER tenant_activity_exceptions AFTER INSERT OR UPDATE OR DELETE ON exception_events
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('exception', 'carrier_org_id');
CREATE TRIGGER tenant_activity_support_tickets AFTER INSERT OR UPDATE OR DELETE ON support_tickets
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('support_ticket', 'carrier_org_id');
CREATE TRIGGER tenant_activity_support_messages AFTER INSERT OR UPDATE OR DELETE ON support_ticket_messages
  FOR EACH ROW EXECUTE FUNCTION capture_tenant_activity('support_message', 'carrier_org_id');
CREATE TRIGGER tenant_activity_load_events AFTER INSERT OR UPDATE OR DELETE ON load_events
  FOR EACH ROW EXECUTE FUNCTION capture_load_event_activity();
